# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd0f4d818f7d8139fcaa9fa0f26fdfd4772a82cf6253a49240d37ab8eca8a2e39491377c7dc063b2a1d15465243e64b69502307114e1dae67e13a2ed1ab4c92

test:
  secret_key_base: a3cd305a4f1dd320c3b8b79ca3a522a302ed625d7e45d7a348b6c04cbb5e1ae3c08b950a685614d35d7610ef73806713bbaebef032c78fa765d02121e2f5f447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
